services:
  - type: web
    name: job-tracker-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MONGO_URI
        value: your_mongodb_uri
      - key: JWT_SECRET
        value: your_jwt_secret 